[package]
name = "makemkv"
description = "Handles running MakeMKV for copying discs."
authors.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
